### ISSUE TITLE
[RFE] Test secondary interface

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/k8s-netperf#107]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Allow for a secondary interface to be used for throughput testing

**Comment by jtaleric** [comment]
To do this 
1 ) Update the confg yaml to include a `multus` option. Like
```
---
tests:
  - TCPStream:
    parallelism: 1
    profile: "TCP_STREAM"
    duration: 10
    samples: 3
    messagesize: 1024
    multus: <net-attach-name>
```

2 ) update the client/server podSpec to include the `cncf.io/networks` annotation for the user-defined net-attach interface

3) capture the ip address of the multus interface.
