### ISSUE TITLE
would violate PodSecurity "restricted:latest": host namespaces

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/k8s-netperf#31]
Running k8s-netperf i see 
```
W0303 20:40:52.141105 1839294 warnings.go:70] would violate PodSecurity "restricted:latest": host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "client-host" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "client-host" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "client-host" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "client-host" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

```

**Comment by jtaleric** [comment]
Just a documentation thing unless we start creating the NS and SA for the user.

**Comment by paigerube14** [comment]
If you create the namespace with these labels I think we would not get the error message mentioned above: 

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: <name>
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: “false”
  name: <name>
```
